### ISSUE TITLE
Rocket sprite is displayed incorrectly.

### ISSUE THREAD

**Issue by BreadSniper** [BregoX/instantrockets#1]
Rocket sprite seems to be trimmed and has a part of the pipe in it.
<img width="313" alt="screen shot 2017-07-15 at 1 36 35 am" src="https://user-images.githubusercontent.com/23015779/28233234-19230adc-68fe-11e7-88fc-f6d002d0583a.png">

**Comment by BregoX** [comment]
Fixed
